version: '3'
services:
   mariadb:
      environment:
         MYSQL_ROOT_PASSWORD: root
      image : "mariadb:latest"
      networks:
         - test
      container_name: mariadb
      volumes:
         - "dbdata:/var/lib/mysql"
         - "../social-app/dumps:/docker-entrypoint-initdb.d"
   social-app:
      build: ../social-app
      image: abstractalchemist/social-app:latest
      networks:
         - test
      container_name: social-app
      volumes:
         - "../social-app/src:/app/src"
      depends_on:
          - "mariadb"
   social-client:
      build: ../social-client
      ports:
         - "8080:80"
      image: abstractalchemist/social-client:latest
      volumes:
         - "../social-client/build:/usr/share/nginx/html"
      networks:
         - test
      container_name: social-client
      depends_on:
         - social-app
networks:
   test:
volumes:
   dbdata: